=== Sasikuttan2163/dvalin-data/schemas/FishingRod.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "_id": {
            "type": "number"
        },
        "description": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "rarity": {
            "type": "number"
        },
        "source": {
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "required": [
        "_id",
        "description",
        "id",
        "name",
        "rarity",
        "source"
    ],
    "type": "object"
}

=== Sasikuttan2163/dvalin-data/data/ES/WeaponSecondaryMaterial/OldOperativesPocketWatch.json
{
  "_id": 112092,
  "id": "old_operatives_pocket_watch",
  "name": "Reloj de bolsillo vetusto de Senescal",
  "description": "El desgaste y el óxido de la insignia de la carcasa reflejan fielmente sus días como ejecutoras.",
  "source": [
    "Obtenido de Soldados Fatui - Senescales",
    "Canjear Polvo estelar"
  ],
  "rarity": 2
}
