=== Sasikuttan2163/dvalin-data/schemas/Fish.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "_id": {
      "type": "number"
    },
    "bait": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "rarity": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "name",
        "rarity"
      ],
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "_id",
    "bait",
    "description",
    "id",
    "name",
    "rarity",
    "source"
  ],
  "type": "object",
  "additionalProperties": false
}

=== Sasikuttan2163/dvalin-data/data/ES/Fish/Dawncatcher.json
{
	"_id": 131004,
	"id": "Dawncatcher",
	"name": "Atrapaauroras",
	"description": "Una subespecie de medaka con escamas relucientes. Parece ser una variación de los medakas normales, pero su apariencia y sus costumbres son muy distintas.<br/>Hay un rumor sobre la supuesta habilidad de estos peces para predecir el tiempo: si saltan del agua para rozar la primera luz del amanecer que atraviesa los cielos, será un día soleado.",
	"rarity": 3,
	"source": [
		"Pescar"
	],
	"bait": {
		"_id": 111023,
		"id": "FruitPasteBait",
		"name": "Cebo afrutado",
		"rarity": 2
	}
}
