=== Sasikuttan2163/dvalin-data/schemas/Ingredients.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "_id": {
            "type": "number"
        },
        "description": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "processing": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "amount": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "amount",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "recipes": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "source": {
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "required": [
        "_id",
        "description",
        "id",
        "name"
    ],
    "type": "object"
}

=== Sasikuttan2163/dvalin-data/data/PT/Ingredient/Potato.json
{
	"_id": 100080,
	"id": "Potato",
	"name": "Batata",
	"description": "É uma planta perene da família das solanáceas. Um presente da terra devido aos seus vários métodos de preparado.",
	"recipes": [
		{
			"_id": 1401,
			"id": "DuckConfit",
			"name": "Confit de Pato"
		},
		{
			"_id": 2007,
			"id": "SatisfyingSalad",
			"name": "Salada Saudável"
		},
		{
			"_id": 2010,
			"id": "FragrantMashedPotatoes",
			"name": "Purê de Batatas Aromatizado"
		},
		{
			"_id": 2107,
			"id": "GoldenShrimpBalls",
			"name": "Almôndegas Douradas de Camarão"
		},
		{
			"_id": 2110,
			"id": "StoneHarborDelicacies",
			"name": "Iguarias do Porto de Pedra"
		},
		{
			"_id": 2303,
			"id": "MasalaCheeseBalls",
			"name": "Bolinhas de Queijo ao Masala"
		},
		{
			"_id": 2305,
			"id": "Panipuri",
			"name": "Panipuri"
		},
		{
			"_id": 3007,
			"id": "MondstadtHashBrown",
			"name": "Bolinho de Batata de Mondstadt"
		},
		{
			"_id": 3008,
			"id": "PileEmUp",
			"name": "\"Empilhar\""
		},
		{
			"_id": 3009,
			"id": "BarbatosRatatouille",
			"name": "Ensopado do Arconte Anemo"
		},
		{
			"_id": 3013,
			"id": "CrispyPotatoShrimpPlatter",
			"name": "Prato de Camarão e Batata Crocante"
		},
		{
			"_id": 3210,
			"id": "BraisedMeat",
			"name": "Carne Bestial Vermelha"
		},
		{
			"_id": 3218,
			"id": "SakuraShrimpCrackers",
			"name": "Biscoitos de Sakura e Camarão"
		},
		{
			"_id": 3304,
			"id": "PotatoBoat",
			"name": "Navio de Batata"
		},
		{
			"_id": 3402,
			"id": "FishAndChips",
			"name": "Peixe e Batatas Fritas"
		},
		{
			"_id": 3418,
			"id": "Feastos",
			"name": "Redondinho"
		},
		{
			"_id": 4402,
			"id": "Haggis",
			"name": "Haggis"
		}
	],
	"source": [
		"Vendido nas Tendas"
	]
}

=== Sasikuttan2163/dvalin-data/data/VI/Ingredient/Bacon.json
{
	"_id": 110010,
	"id": "Bacon",
	"name": "Thịt Xông Khói",
	"description": "Thịt pha gân được hun khói. Nhiều lớp, béo mà không ngán, rất được yêu thích.",
	"processing": [
		{
			"_id": 100061,
			"id": "RawMeat",
			"name": "Thịt Rừng",
			"amount": 2
		},
		{
			"_id": 100075,
			"id": "Salt",
			"name": "Muối",
			"amount": 2
		}
	],
	"recipes": [
		{
			"_id": 3003,
			"id": "ColdCutPlatter",
			"name": "Thịt Lạnh"
		},
		{
			"_id": 3215,
			"id": "Moreandmore",
			"name": "Toto Nướng"
		},
		{
			"_id": 3404,
			"id": "PoissonchantPie",
			"name": "Bánh Poissonchant"
		},
		{
			"_id": 3412,
			"id": "TomatesNarbonnaises",
			"name": "Cà Dồn Narbonnaise"
		}
	],
	"source": [
		"Nhận khi gia công nấu nướng"
	]
}

=== Sasikuttan2163/dvalin-data/data/ZH-S/Ingredient/Almond.json
{
	"_id": 100089,
	"id": "Almond",
	"name": "杏仁",
	"description": "有着奇特香味的种子。能给食物带来全然不同的清新风味。",
	"recipes": [
		{
			"_id": 1402,
			"id": "TroutAmandine",
			"name": "杏仁鳟鱼"
		},
		{
			"_id": 2101,
			"id": "AlmondTofu",
			"name": "杏仁豆腐"
		},
		{
			"_id": 3108,
			"id": "LotusFlowerCrisp",
			"name": "莲花酥"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "枣椰蜜糖"
		},
		{
			"_id": 3416,
			"id": "LaLettreAFocalors",
			"name": "致水神"
		},
		{
			"_id": 3419,
			"id": "RainbowMacarons",
			"name": "缤纷马卡龙"
		}
	],
	"source": [
		"璃月杂货店购买",
		"枫丹杂货店购买"
	]
}

=== Sasikuttan2163/dvalin-data/data/KO/Ingredient/GlabrousBeans.json
{
	"_id": 100096,
	"id": "GlabrousBeans",
	"name": "반질반질콩",
	"description": "티바트에서 흔히 볼 수 있는 콩류 작물. 은은한 향을 풍기고 있으며 활용 방법이 다양한 덕분에 각지의 주민들에게 인기를 끌고 있다",
	"recipes": [
		{
			"_id": 1301,
			"id": "MintyBeanSoup",
			"name": "완두콩 민트 수프"
		},
		{
			"_id": 2305,
			"id": "Panipuri",
			"name": "파니푸리"
		},
		{
			"_id": 2308,
			"id": "AaruMixedRice",
			"name": "아루 비빔밥"
		},
		{
			"_id": 2311,
			"id": "Fatteh",
			"name": "팟타"
		},
		{
			"_id": 3414,
			"id": "Cassoulet",
			"name": "카술레"
		}
	],
	"source": [
		"수메르 레스토랑 구매",
		"폰타인 잡화점 구매"
	]
}

=== Sasikuttan2163/dvalin-data/data/VI/Ingredient/AjilenakhNut.json
{
	"_id": 101221,
	"id": "AjilenakhNut",
	"name": "Quả Ajilenakh",
	"description": "Quả của cây thường xanh trong ốc đảo sa mạc. Dưới lớp vỏ cứng là lớp thịt dày, ngọt và thơm ngon, là nguồn lương thực quan trọng của người dân nơi biển cát.",
	"recipes": [
		{
			"_id": 3307,
			"id": "Baklava",
			"name": "Baklava"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "Ajilenakh Ngào Đường"
		},
		{
			"_id": 3310,
			"id": "CharcoalbakedAjilenakhCake",
			"name": "Bánh Ajilenakh Nướng"
		}
	],
	"source": [
		"Thu thập ở ốc đảo sa mạc Sumeru"
	]
}

=== Sasikuttan2163/dvalin-data/data/RU/Ingredient/Rice.json
{
	"_id": 100092,
	"id": "Rice",
	"name": "Рис",
	"description": "Зерновая культура, широко распространённая в Тейвате. Нет человека, который не восхищался бы формой и питательностью рисовых зёрен. Вот почему часто говорят: «Один и тот же рис способен вскормить сотню разных людей»",
	"recipes": [
		{
			"_id": 1104,
			"id": "RiceBuns",
			"name": "Рисовые пампушки"
		},
		{
			"_id": 1204,
			"id": "SweetShrimpSushi",
			"name": "Суши с креветками"
		},
		{
			"_id": 1205,
			"id": "BirdEggSushi",
			"name": "Яичные суши"
		},
		{
			"_id": 2105,
			"id": "CrystalShrimp",
			"name": "Кристальные баоцзы"
		},
		{
			"_id": 2113,
			"id": "StirfriedFishNoodles",
			"name": "Жареная лапша с рыбой"
		},
		{
			"_id": 2201,
			"id": "TunaSushi",
			"name": "Суши с тунцом"
		},
		{
			"_id": 2202,
			"id": "Onigiri",
			"name": "Онигири"
		},
		{
			"_id": 2208,
			"id": "BerryMizuManjuu",
			"name": "Ягодный мидзу мандзю"
		},
		{
			"_id": 2308,
			"id": "AaruMixedRice",
			"name": "Пилав Аару"
		},
		{
			"_id": 3105,
			"id": "ComeAndGetIt",
			"name": "Налетайка"
		},
		{
			"_id": 3109,
			"id": "UniversalPeace",
			"name": "«Благоденствие»"
		},
		{
			"_id": 3110,
			"id": "JueyunGuoba",
			"name": "Заоблачный гоба"
		},
		{
			"_id": 3201,
			"id": "TricolorDango",
			"name": "Трёхцветное данго"
		},
		{
			"_id": 3205,
			"id": "SakuraMochi",
			"name": "Моти с сакурой"
		},
		{
			"_id": 3209,
			"id": "RicePudding",
			"name": "Рисовый пудинг"
		},
		{
			"_id": 3212,
			"id": "InvigoratingKittyMeal",
			"name": "Бодрящее кошачье лакомство"
		},
		{
			"_id": 3213,
			"id": "OmeletteRice",
			"name": "Рисовый омлет"
		},
		{
			"_id": 3216,
			"id": "UnagiChazuke",
			"name": "Унаги тядзукэ"
		},
		{
			"_id": 3303,
			"id": "Tahchin",
			"name": "Тахчин"
		},
		{
			"_id": 4301,
			"id": "Biryani",
			"name": "Бирьяни"
		}
	],
	"source": [
		"Лавки Ли Юэ",
		"Торговые лавки Инадзумы",
		"Лавки Сумеру"
	]
}

=== Sasikuttan2163/dvalin-data/data/PT/Ingredient/ZaytunPeach.json
{
	"_id": 101218,
	"id": "ZaytunPeach",
	"name": "Pêssego Zaytun",
	"description": "Fruto de um arbusto na floresta. A sua carne é firme e o sabor é doce. Dizem que serve para tranquilizar a mente.",
	"recipes": [
		{
			"_id": 2302,
			"id": "SelvaSalad",
			"name": "Salada Tropical"
		}
	],
	"source": [
		"Encontrado na natureza"
	]
}

=== Sasikuttan2163/dvalin-data/data/EN/Ingredient/CoffeeBeans.json
{
	"_id": 100098,
	"id": "CoffeeBeans",
	"name": "Coffee Beans",
	"description": "A common fruit in Teyvat with a special aroma. It can be used to make beverages after being ground.",
	"recipes": [
		{
			"_id": 3314,
			"id": "Tulumba",
			"name": "Tulumba"
		},
		{
			"_id": 3410,
			"id": "CoffeeBavarois",
			"name": "Coffee Bavarois"
		},
		{
			"_id": 3416,
			"id": "LaLettreAFocalors",
			"name": "La Lettre a Focalors"
		}
	],
	"source": [
		"Sold at cafés in Sumeru",
		"Sold at cafés in Fontaine"
	]
}
