=== Sasikuttan2163/dvalin-data/schemas/Ingredients.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "_id": {
            "type": "number"
        },
        "description": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "processing": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "amount": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "amount",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "recipes": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "source": {
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "required": [
        "_id",
        "description",
        "id",
        "name"
    ],
    "type": "object"
}

=== Sasikuttan2163/dvalin-data/data/TR/Ingredient/FermentedJuice.json
{
	"_id": 100099,
	"id": "FermentedJuice",
	"name": "Fermented Juice",
	"description": "น้ำผลไม้จากการหมักบ่ม ที่มีกลิ่นหอมอันเป็นเอกลักษณ์ของผลไม้ มักจะใช้ปรุงรสตอนทำอาหารเมนูเนื้อสัตว์",
	"recipes": [
		{
			"_id": 3411,
			"id": "TripesDuPort",
			"name": "Tripes du Port"
		},
		{
			"_id": 4401,
			"id": "VessieChicken",
			"name": "Vessie Chicken"
		}
	],
	"source": [
		"ซื้อจากร้านขายของชำใน Fontaine"
	]
}

=== Sasikuttan2163/dvalin-data/data/FR/Ingredient/SumeruRose.json
{
	"_id": 101219,
	"id": "SumeruRose",
	"name": "Rose sumérienne",
	"description": "Vives et belles, ces fleurs d'un violet pur dégagent un parfum agréable qui fera s'arrêter toute personne passant devant elles. Leur nom peut porter à confusion, car bien qu'elles soient des roses, elles sont semblables à nulle autre fleur de la même classification florale.",
	"recipes": [
		{
			"_id": 1302,
			"id": "LambadFishRoll",
			"name": "Rouleau au poisson de Lambad"
		},
		{
			"_id": 2302,
			"id": "SelvaSalad",
			"name": "Salade de selve"
		},
		{
			"_id": 2309,
			"id": "RoseCustard",
			"name": "Crème à la rose"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "Nougat d'ajilenakh"
		},
		{
			"_id": 3309,
			"id": "PadisarahPudding",
			"name": "Pudding de padisachidées"
		}
	],
	"source": [
		"Dans la nature"
	]
}

=== Sasikuttan2163/dvalin-data/data/FR/Ingredient/AjilenakhNut.json
{
	"_id": 101221,
	"id": "AjilenakhNut",
	"name": "Noix d'ajilenakh",
	"description": "Un fruit qui pousse sur les arbres à feuilles persistantes dans les oasis du désert. La chair sous sa peau dure est épaisse, sucrée et délicieuse, ce qui en fait une source de nourriture importante parmi les peuples du désert.",
	"recipes": [
		{
			"_id": 3307,
			"id": "Baklava",
			"name": "Baklava"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "Nougat d'ajilenakh"
		},
		{
			"_id": 3310,
			"id": "CharcoalbakedAjilenakhCake",
			"name": "Charbon d'ajilenakh"
		}
	],
	"source": [
		"Oasis des déserts de Sumeru"
	]
}

=== Sasikuttan2163/dvalin-data/data/EN/Ingredient/Cabbage.json
{
	"_id": 100018,
	"id": "Cabbage",
	"name": "Cabbage",
	"description": "A layered, leafy vegetable. Said to have originally been an ornamental plant, it certainly looks great in the pot.",
	"recipes": [
		{
			"_id": 2003,
			"id": "NorthernSmokedChicken",
			"name": "Northern Smoked Chicken"
		},
		{
			"_id": 2007,
			"id": "SatisfyingSalad",
			"name": "Satisfying Salad"
		},
		{
			"_id": 2203,
			"id": "MixedYakisoba",
			"name": "Mixed Yakisoba"
		},
		{
			"_id": 2211,
			"id": "KatsuSandwich",
			"name": "Katsu Sandwich"
		},
		{
			"_id": 3005,
			"id": "CrabHamVeggieBake",
			"name": "Crab, Ham & Veggie Bake"
		},
		{
			"_id": 3006,
			"id": "MushroomPizza",
			"name": "Mushroom Pizza"
		},
		{
			"_id": 3014,
			"id": "GoldenChickenBurger",
			"name": "Golden Chicken Burger"
		},
		{
			"_id": 3104,
			"id": "QingceStirFry",
			"name": "Qingce Stir Fry"
		},
		{
			"_id": 4101,
			"id": "JadeParcels",
			"name": "Jade Parcels"
		},
		{
			"_id": 4203,
			"id": "ChiliminceCornbreadBuns",
			"name": "Chili-Mince Cornbread Buns"
		}
	],
	"source": [
		"Found in the wild",
		"Sold at general goods shops"
	]
}

=== Sasikuttan2163/dvalin-data/data/KO/Ingredient/Radish.json
{
	"_id": 100014,
	"id": "Radish",
	"name": "흰 무",
	"description": "섬유질이 풍부한 초본식물. 쉽게 재배할 수 있으며, 섬유질과 영양가가 풍부하다",
	"recipes": [
		{
			"_id": 1005,
			"id": "RadishVeggieSoup",
			"name": "무 수프"
		},
		{
			"_id": 2006,
			"id": "FriedRadishBalls",
			"name": "무완자 튀김"
		},
		{
			"_id": 2207,
			"id": "RadishAndFishStew",
			"name": "생선 무조림"
		},
		{
			"_id": 3217,
			"id": "FivePickledTreasures",
			"name": "다섯 보물 쓰케모노"
		},
		{
			"_id": 4201,
			"id": "SashimiPlatter",
			"name": "모둠 회"
		},
		{
			"_id": 4402,
			"id": "Haggis",
			"name": "해기스"
		}
	],
	"source": [
		"야외 채집"
	]
}

=== Sasikuttan2163/dvalin-data/data/KO/Ingredient/Sausage.json
{
	"_id": 110011,
	"id": "Sausage",
	"name": "소시지",
	"description": "창자에 고기를 갈아 넣은 소시지. 저장이 용이하여 고기 애호가들이 일상적으로 즐긴다",
	"processing": [
		{
			"_id": 100061,
			"id": "RawMeat",
			"name": "짐승고기",
			"amount": 3
		}
	],
	"recipes": [
		{
			"_id": 3003,
			"id": "ColdCutPlatter",
			"name": "냉채수육"
		},
		{
			"_id": 3207,
			"id": "RiceCakeSoup",
			"name": "모둠 어묵탕"
		},
		{
			"_id": 3414,
			"id": "Cassoulet",
			"name": "카술레"
		}
	],
	"source": [
		"요리 가공 획득"
	]
}

=== Sasikuttan2163/dvalin-data/data/RU/Ingredient/SmokedFowl.json
{
	"_id": 110003,
	"id": "SmokedFowl",
	"name": "Копчёная птица",
	"description": "Копчёное мясо птицы. Запах дыма придаёт блюдам новый вкус.",
	"processing": [
		{
			"_id": 100064,
			"id": "Fowl",
			"name": "Мясо птицы",
			"amount": 3
		},
		{
			"_id": 100075,
			"id": "Salt",
			"name": "Соль",
			"amount": 1
		}
	],
	"recipes": [
		{
			"_id": 2003,
			"id": "NorthernSmokedChicken",
			"name": "Копчёный цыплёночек"
		}
	],
	"source": [
		"Заготовка ингредиентов"
	]
}

=== Sasikuttan2163/dvalin-data/data/PT/Ingredient/Matsutake.json
{
	"_id": 100063,
	"id": "Matsutake",
	"name": "Matsutake",
	"description": "Um fungo raro que geralmente cresce sobre ou perto de pinheiros. Seu aroma delicado revela sua localização.",
	"recipes": [
		{
			"_id": 2104,
			"id": "MatsutakeMeatRolls",
			"name": "Rolinho de Carne com Matsutake"
		},
		{
			"_id": 2109,
			"id": "VegetarianAbalone",
			"name": "Abalone Vegetariano"
		},
		{
			"_id": 2110,
			"id": "StoneHarborDelicacies",
			"name": "Iguarias do Porto de Pedra"
		},
		{
			"_id": 3002,
			"id": "SautedMatsutake",
			"name": "Matsutake Salteado"
		},
		{
			"_id": 3113,
			"id": "CuredPorkDryHotpot",
			"name": "Porco Curado com Matsutake"
		},
		{
			"_id": 4103,
			"id": "TianshuMeat",
			"name": "Carne de Tianshu"
		},
		{
			"_id": 4202,
			"id": "ButterCrab",
			"name": "Caranguejo na Manteiga"
		},
		{
			"_id": 5101,
			"id": "AdeptusTemptation",
			"name": "Tentação do Adeptus"
		}
	],
	"source": [
		"Encontrado na natureza"
	]
}
