=== Sasikuttan2163/dvalin-data/schemas/Ingredients.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "_id": {
            "type": "number"
        },
        "description": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "processing": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "amount": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "amount",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "recipes": {
            "items": {
                "properties": {
                    "_id": {
                        "type": "number"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "_id",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "source": {
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "required": [
        "_id",
        "description",
        "id",
        "name"
    ],
    "type": "object"
}

=== Sasikuttan2163/dvalin-data/data/JP/Ingredient/SumeruRose.json
{
	"_id": 101219,
	"id": "SumeruRose",
	"name": "スメールローズ",
	"description": "鮮やかな濃い紫色の花。人を立ち止まらせるほどの芳しい香りがする。ローズと呼ばれるが、厳密には玫瑰。",
	"recipes": [
		{
			"_id": 1302,
			"id": "LambadFishRoll",
			"name": "ランバドフィッシュロール"
		},
		{
			"_id": 2302,
			"id": "SelvaSalad",
			"name": "雨林サラダ"
		},
		{
			"_id": 2309,
			"id": "RoseCustard",
			"name": "ローズシュリカンド"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "ナツメヤシキャンディ"
		},
		{
			"_id": 3309,
			"id": "PadisarahPudding",
			"name": "パティサラプリン"
		}
	],
	"source": [
		"野外で採集"
	]
}

=== Sasikuttan2163/dvalin-data/data/TR/Ingredient/SumeruRose.json
{
	"_id": 101219,
	"id": "SumeruRose",
	"name": "Sumeru Rose",
	"description": "ดอกไม้สีม่วงที่ทั้งสดใสและสุขุม แผ่กลิ่นอายหอมหวนที่ทำให้ผู้คนต้องเหลียวกลับมามอง ถึงแม้จะได้ชื่อว่ากุหลาบ แต่แท้จริงแล้วเป็นดอกไม้ตระกูลอื่น",
	"recipes": [
		{
			"_id": 1302,
			"id": "LambadFishRoll",
			"name": "Lambad Fish Roll"
		},
		{
			"_id": 2302,
			"id": "SelvaSalad",
			"name": "Selva Salad"
		},
		{
			"_id": 2309,
			"id": "RoseCustard",
			"name": "Rose Custard"
		},
		{
			"_id": 3308,
			"id": "CandiedAjilenakhNut",
			"name": "Candied Ajilenakh Nut"
		},
		{
			"_id": 3309,
			"id": "PadisarahPudding",
			"name": "Padisarah Pudding"
		}
	],
	"source": [
		"พบได้ในโลกกว้าง"
	]
}

=== Sasikuttan2163/dvalin-data/data/ES/Ingredient/Bacon.json
{
	"_id": 110010,
	"id": "Bacon",
	"name": "Tocino",
	"description": "Tiras de cerdo curadas. Crujientes y un poco grasientas.",
	"processing": [
		{
			"_id": 100061,
			"id": "RawMeat",
			"name": "Carne cruda",
			"amount": 2
		},
		{
			"_id": 100075,
			"id": "Salt",
			"name": "Sal",
			"amount": 2
		}
	],
	"recipes": [
		{
			"_id": 3003,
			"id": "ColdCutPlatter",
			"name": "Plato de carnes frías"
		},
		{
			"_id": 3215,
			"id": "Moreandmore",
			"name": "Más y más"
		},
		{
			"_id": 3404,
			"id": "PoissonchantPie",
			"name": "Pastel pezcanto"
		},
		{
			"_id": 3412,
			"id": "TomatesNarbonnaises",
			"name": "Tomates Narbonnais"
		}
	],
	"source": [
		"Procesar comida"
	]
}

=== Sasikuttan2163/dvalin-data/data/FR/Ingredient/Cheese.json
{
	"_id": 110009,
	"id": "Cheese",
	"name": "Fromage",
	"description": "Produit à base de lait fermenté. Il peut être utilisé de façons variées pour agrémenter vos plats.",
	"processing": [
		{
			"_id": 100078,
			"id": "Milk",
			"name": "Lait",
			"amount": 3
		}
	],
	"recipes": [
		{
			"_id": 2303,
			"id": "MasalaCheeseBalls",
			"name": "Boules de fromage au masala"
		},
		{
			"_id": 2404,
			"id": "FontainianOnionSoup",
			"name": "Soupe fontainoise à l'oignon"
		},
		{
			"_id": 3006,
			"id": "MushroomPizza",
			"name": "Pizza aux champignons"
		},
		{
			"_id": 3008,
			"id": "PileEmUp",
			"name": "Empil'tout"
		},
		{
			"_id": 3304,
			"id": "PotatoBoat",
			"name": "Bateau-patate"
		},
		{
			"_id": 3306,
			"id": "MilkyMushroomCrispTower",
			"name": "Tour de champignons au lait"
		},
		{
			"_id": 3403,
			"id": "Lasagna",
			"name": "Lasagnes"
		},
		{
			"_id": 4205,
			"id": "SuperMagnificentPizza",
			"name": "Super pizza suprême"
		},
		{
			"_id": 4303,
			"id": "MeatLoversMushroomPizza",
			"name": "Pizza champignons-viande"
		}
	],
	"source": [
		"Cuisine (préparation)"
	]
}

=== Sasikuttan2163/dvalin-data/data/ZH-T/Ingredient/Onion.json
{
	"_id": 100076,
	"id": "Onion",
	"name": "洋蔥",
	"description": "球狀的草本植物。為了報復切碎它的人，不管人的心情好壞都會讓他落淚。",
	"recipes": [
		{
			"_id": 2003,
			"id": "NorthernSmokedChicken",
			"name": "北地煙燻雞"
		},
		{
			"_id": 2008,
			"id": "FishermansToast",
			"name": "漁人吐司"
		},
		{
			"_id": 2306,
			"id": "CurryShrimp",
			"name": "咖哩蝦"
		},
		{
			"_id": 2403,
			"id": "TassesRagout",
			"name": "塔塞斯雜燴"
		},
		{
			"_id": 2404,
			"id": "FontainianOnionSoup",
			"name": "楓丹洋蔥湯"
		},
		{
			"_id": 3009,
			"id": "BarbatosRatatouille",
			"name": "風神雜燴菜"
		},
		{
			"_id": 3210,
			"id": "BraisedMeat",
			"name": "紅燴獸肉"
		},
		{
			"_id": 3312,
			"id": "SabzMeatStew",
			"name": "薩布茲燉肉"
		},
		{
			"_id": 3313,
			"id": "ScentedMeatBalls",
			"name": "秘香肉團"
		},
		{
			"_id": 3315,
			"id": "GildedTajine",
			"name": "鍍金鍋"
		},
		{
			"_id": 3406,
			"id": "SteakTartare",
			"name": "生肉塔塔"
		},
		{
			"_id": 3411,
			"id": "TripesDuPort",
			"name": "港灣牛肚"
		},
		{
			"_id": 3412,
			"id": "TomatesNarbonnaises",
			"name": "納博內番茄盅"
		},
		{
			"_id": 3418,
			"id": "Feastos",
			"name": "圈圈圓圓"
		},
		{
			"_id": 4204,
			"id": "BountifulYear",
			"name": "豐年有餘"
		}
	],
	"source": [
		"雜貨店購買"
	]
}

=== Sasikuttan2163/dvalin-data/data/VI/Ingredient/Mint.json
{
	"_id": 100016,
	"id": "Mint",
	"name": "Bạc Hà",
	"description": "Loại lá có thành phần làm mát. Mùi vị thanh mát sảng khoái đánh tan cái nóng của mùa hè.",
	"recipes": [
		{
			"_id": 1005,
			"id": "RadishVeggieSoup",
			"name": "Canh Rau Củ"
		},
		{
			"_id": 1007,
			"id": "MintJelly",
			"name": "Thạch Bạc Hà"
		},
		{
			"_id": 1301,
			"id": "MintyBeanSoup",
			"name": "Canh Đậu Bạc Hà"
		},
		{
			"_id": 2111,
			"id": "MintSalad",
			"name": "Rau Trộn Bạc Hà"
		},
		{
			"_id": 2302,
			"id": "SelvaSalad",
			"name": "Salad Nhiệt Đới"
		},
		{
			"_id": 2307,
			"id": "FishWithCreamSauce",
			"name": "Cá Tươi Sốt Kem"
		},
		{
			"_id": 2311,
			"id": "Fatteh",
			"name": "Fatteh"
		},
		{
			"_id": 3001,
			"id": "CallaLilySeafoodSoup",
			"name": "Súp Hải Sản Hoa Calla Lily"
		},
		{
			"_id": 3003,
			"id": "ColdCutPlatter",
			"name": "Thịt Lạnh"
		},
		{
			"_id": 3013,
			"id": "CrispyPotatoShrimpPlatter",
			"name": "Giỏ Khoai Giòn Tôm Tươi"
		},
		{
			"_id": 3112,
			"id": "MintyMeatRolls",
			"name": "Thịt Rừng Cuộn Bạc Hà"
		},
		{
			"_id": 3220,
			"id": "RainbowAster",
			"name": "Tử Uyển Cầu Vồng"
		},
		{
			"_id": 3316,
			"id": "MintyFruitTea",
			"name": "Trà Trái Cây Bạc Hà"
		},
		{
			"_id": 3407,
			"id": "PoissonSeafoodSoup",
			"name": "Súp Hải Sản Poisson"
		}
	],
	"source": [
		"Thu Thập Bên Ngoài"
	]
}

=== Sasikuttan2163/dvalin-data/data/RU/Ingredient/Seagrass.json
{
	"_id": 101210,
	"id": "Seagrass",
	"name": "Морская водоросль",
	"description": "Произрастает на морском мелководье. Придаёт блюдам своеобразный вкус.",
	"recipes": [
		{
			"_id": 1203,
			"id": "MisoSoup",
			"name": "Мисо-суп"
		},
		{
			"_id": 1206,
			"id": "SobaNoodles",
			"name": "Соба"
		},
		{
			"_id": 2202,
			"id": "Onigiri",
			"name": "Онигири"
		},
		{
			"_id": 2206,
			"id": "Wakatakeni",
			"name": "Вакатакэни"
		},
		{
			"_id": 2210,
			"id": "UdonNoodles",
			"name": "Лапша удон"
		},
		{
			"_id": 3212,
			"id": "InvigoratingKittyMeal",
			"name": "Бодрящее кошачье лакомство"
		},
		{
			"_id": 3216,
			"id": "UnagiChazuke",
			"name": "Унаги тядзукэ"
		},
		{
			"_id": 3217,
			"id": "FivePickledTreasures",
			"name": "Пять драгоценных солений"
		},
		{
			"_id": 4202,
			"id": "ButterCrab",
			"name": "Краб в масле"
		}
	],
	"source": [
		"Акватория Инадзумы"
	]
}

=== Sasikuttan2163/dvalin-data/data/KO/Ingredient/Fish.json
{
	"_id": 100084,
	"id": "Fish",
	"name": "생선 살코기",
	"description": "생선의 신선한 살코기. 적절히 조리하면 아주 맛있는 요리가 된다",
	"processing": [
		{
			"_id": 131000,
			"id": "Medaka",
			"name": "구피",
			"amount": 1
		}
	],
	"recipes": [
		{
			"_id": 1006,
			"id": "MondstadtGrilledFish",
			"name": "몬드 생선구이"
		},
		{
			"_id": 1103,
			"id": "GrilledTigerFish",
			"name": "흘호어 구이"
		},
		{
			"_id": 1202,
			"id": "DrybraisedSaltedFish",
			"name": "은어조림"
		},
		{
			"_id": 1302,
			"id": "LambadFishRoll",
			"name": "람바드 생선 롤"
		},
		{
			"_id": 1402,
			"id": "TroutAmandine",
			"name": "송어 아망딘"
		},
		{
			"_id": 2113,
			"id": "StirfriedFishNoodles",
			"name": "생선 볶음면"
		},
		{
			"_id": 2201,
			"id": "TunaSushi",
			"name": "참치 초밥"
		},
		{
			"_id": 2202,
			"id": "Onigiri",
			"name": "주먹밥"
		},
		{
			"_id": 2207,
			"id": "RadishAndFishStew",
			"name": "생선 무조림"
		},
		{
			"_id": 2209,
			"id": "Sangayaki",
			"name": "산가야키"
		},
		{
			"_id": 2210,
			"id": "UdonNoodles",
			"name": "우동"
		},
		{
			"_id": 2307,
			"id": "FishWithCreamSauce",
			"name": "크림소스 생선"
		},
		{
			"_id": 2406,
			"id": "FontaineAspic",
			"name": "아스픽"
		},
		{
			"_id": 3012,
			"id": "SunshineSprat",
			"name": "버터 생선 구이"
		},
		{
			"_id": 3101,
			"id": "ZhongyuanChopSuey",
			"name": "중원 내장꼬치"
		},
		{
			"_id": 3102,
			"id": "BlackbackPerchStew",
			"name": "삶은 검정 농어"
		},
		{
			"_id": 3103,
			"id": "SquirrelFish",
			"name": "탕수어"
		},
		{
			"_id": 3105,
			"id": "ComeAndGetIt",
			"name": "흥얼채"
		},
		{
			"_id": 3111,
			"id": "FullmoonEgg",
			"name": "명월 딤섬"
		},
		{
			"_id": 3207,
			"id": "RiceCakeSoup",
			"name": "모둠 어묵탕"
		},
		{
			"_id": 3212,
			"id": "InvigoratingKittyMeal",
			"name": "활력충만 고양이 밥"
		},
		{
			"_id": 3215,
			"id": "Moreandmore",
			"name": "다다야끼"
		},
		{
			"_id": 3303,
			"id": "Tahchin",
			"name": "타친"
		},
		{
			"_id": 3402,
			"id": "FishAndChips",
			"name": "피시 앤 칩스"
		},
		{
			"_id": 3404,
			"id": "PoissonchantPie",
			"name": "물고기 영창 파이"
		},
		{
			"_id": 3407,
			"id": "PoissonSeafoodSoup",
			"name": "푸아송 해물 수프"
		},
		{
			"_id": 3418,
			"id": "Feastos",
			"name": "동글동글"
		},
		{
			"_id": 4201,
			"id": "SashimiPlatter",
			"name": "모둠 회"
		},
		{
			"_id": 4204,
			"id": "BountifulYear",
			"name": "풍요로운 한 해"
		}
	],
	"source": [
		"어류를 포획하여 채집"
	]
}
