=== Sasikuttan2163/dvalin-data/schemas/Potion.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "_id": {
      "type": "number"
    },
    "craft": {
      "properties": {
        "cost": {
          "type": "number"
        },
        "items": {
          "items": {
            "properties": {
              "_id": {
                "type": "number"
              },
              "amount": {
                "type": "number"
              },
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "_id",
              "amount",
              "id",
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "cost",
        "items"
      ],
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "effect": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    }
  },
  "required": [
    "_id",
    "craft",
    "description",
    "effect",
    "id",
    "name",
    "rarity"
  ],
  "type": "object",
  "additionalProperties": false
}

=== Sasikuttan2163/dvalin-data/data/TR/Potion/InsulationPotion.json
{
	"_id": 111010,
	"id": "InsulationPotion",
	"name": "Insulation Potion",
	"description": "ยาน้ำสำหรับป้องกันไฟฟ้า สามารถเพิ่มความต้านทานไฟฟ้าได้ <br/>เมื่อดื่มจะให้ความรู้สึกซ่าๆ ว่ากันว่ายานี้จะช่วยเพิ่มความต้าน ไฟฟ้าให้แก่ผู้ที่ดื่ม จึงสามารถลดความเสียหายจากการถูกโจมตีด้วยไฟฟ้าได้",
	"effect": "เพิ่มความต้านทานไฟฟ้าให้แก่สมาชิกทีมทุกคน 25% เป็นเวลา 300 วินาที",
	"craft": {
		"cost": 100,
		"items": [
			{
				"_id": 100072,
				"id": "ButterflyWings",
				"name": "Butterfly Wings",
				"amount": 1
			},
			{
				"_id": 100054,
				"id": "ElectroCrystal",
				"name": "Electro Crystal",
				"amount": 1
			}
		]
	},
	"rarity": 3
}

=== Sasikuttan2163/dvalin-data/data/EN/Potion/FrostshieldPotion.json
{
	"_id": 111008,
	"id": "FrostshieldPotion",
	"name": "Frostshield Potion",
	"description": "A miraculous potion that boosts Cryo RES and makes one able to withstand extreme cold.<br/>Induces a chilling sensation when drank, but once this sensation spreads throughout the body, the feeling of being cold disappears.",
	"effect": "Increases all party members' Cryo RES by 25% for 300s.",
	"craft": {
		"cost": 100,
		"items": [
			{
				"_id": 100085,
				"id": "CrystalCore",
				"name": "Crystal Core",
				"amount": 1
			},
			{
				"_id": 100052,
				"id": "MistFlowerCorolla",
				"name": "Mist Flower Corolla",
				"amount": 1
			}
		]
	},
	"rarity": 3
}

=== Sasikuttan2163/dvalin-data/data/IT/Potion/StreamingEssentialOil.json
{
	"_id": 111014,
	"id": "StreamingEssentialOil",
	"name": "Olio essenziale idratante",
	"description": "Conferisce maggiore affinità a Hydro, aumentando i DAN da Hydro.<br/>È una medicina oleosa per uso esterno. Permette di incanalare al meglio l'energia di Hydro. Ha un profumo lieve.",
	"effect": "Aumenta di un 25% i DAN da Hydro di tutti i membri del gruppo per 300 s.",
	"craft": {
		"cost": 100,
		"items": [
			{
				"_id": 100081,
				"id": "Frog",
				"name": "Rana",
				"amount": 1
			},
			{
				"_id": 100026,
				"id": "LotusHead",
				"name": "Frutto di loto",
				"amount": 1
			}
		]
	},
	"rarity": 3
}

=== Sasikuttan2163/dvalin-data/data/FR/Potion/DesiccantPotion.json
{
	"_id": 111007,
	"id": "DesiccantPotion",
	"name": "Potion de résistance Hydro",
	"description": "Une potion mystérieuse qui permet de résister aux environnements humides et augmente la RÉS Hydro.<br/>Cette potion agit comme dessicateur, et est particulièrement utile pour la conservation des objets ; elle peut être ingérée pour le même effet.",
	"effect": "Augmente les RÉS Hydro de tous les personnages de l'équipe de 25 % pendant 300 s.",
	"craft": {
		"cost": 100,
		"items": [
			{
				"_id": 100072,
				"id": "ButterflyWings",
				"name": "Ailes de papillon",
				"amount": 1
			},
			{
				"_id": 100026,
				"id": "LotusHead",
				"name": "Fruit du lotus",
				"amount": 1
			}
		]
	},
	"rarity": 3
}
