=== Sasikuttan2163/dvalin-data/schemas/WeaponSecondaryMaterial.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "_id": {
      "type": "number"
    },
    "craft": {
      "properties": {
        "cost": {
          "type": "number"
        },
        "items": {
          "items": {
            "properties": {
              "_id": {
                "type": "number"
              },
              "amount": {
                "type": "number"
              },
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "_id",
              "amount",
              "id",
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "cost",
        "items"
      ],
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "_id",
    "description",
    "id",
    "name",
    "rarity",
    "source"
  ],
  "type": "object",
  "additionalProperties": false
}

=== Sasikuttan2163/dvalin-data/data/ZH-S/WeaponSecondaryMaterial/AgentsSacrificialKnife.json
{
	"_id": 112030,
	"id": "AgentsSacrificialKnife",
	"name": "特工祭刀",
	"description": "利用至冬国优越的技术制造的异形兵器，曾经属于某位资深特工。一般人不经训练，根本无法使用这种奇怪的武具。",
	"source": [
		"合成获得",
		"40级以上愚人众·债务处理人掉落",
		"星尘兑换"
	],
	"rarity": 3,
	"craft": {
		"cost": 50,
		"items": [
			{
				"_id": 112029,
				"id": "HuntersSacrificialKnife",
				"name": "猎兵祭刀",
				"amount": 3
			}
		]
	}
}

=== Sasikuttan2163/dvalin-data/data/ES/WeaponSecondaryMaterial/ForeignSynapse.json
{
	"_id": 112090,
	"id": "ForeignSynapse",
	"name": "Sinapsis extrínseca",
	"description": "Tanto el origen como la zona de actividad de estas criaturas tan atípicas se encuentra en Elynas.",
	"source": [
		"Sintetizar",
		"#Obtenido de Protofisuradores (Niv.{NON_BREAK_SPACE}40+)",
		"Canjear Polvo estelar"
	],
	"rarity": 3,
	"craft": {
		"cost": 50,
		"items": [
			{
				"_id": 112089,
				"id": "RiftCore",
				"name": "Núcleo de la fisura",
				"amount": 3
			}
		]
	}
}

=== Sasikuttan2163/dvalin-data/data/ID/WeaponSecondaryMaterial/ForeignSynapse.json
{
	"_id": 112090,
	"id": "ForeignSynapse",
	"name": "Foreign Synapse",
	"description": "Bentuk kehidupan aneh ini berasal dari Elynas dan beraktivitas di area situ juga.",
	"source": [
		"Didapatkan melalui Craft",
		"Dijatuhkan oleh Breacher Primus Lv. 40+",
		"Penukaran Stardust"
	],
	"rarity": 3,
	"craft": {
		"cost": 50,
		"items": [
			{
				"_id": 112089,
				"id": "RiftCore",
				"name": "Rift Core",
				"amount": 3
			}
		]
	}
}
