=== Sasikuttan2163/dvalin-data/schemas/WeaponPrimaryMaterial.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "_id": {
      "type": "number"
    },
    "craft": {
      "properties": {
        "cost": {
          "type": "number"
        },
        "items": {
          "items": {
            "properties": {
              "_id": {
                "type": "number"
              },
              "amount": {
                "type": "number"
              },
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "_id",
              "amount",
              "id",
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": [
        "cost",
        "items"
      ],
      "type": "object"
    },
    "days": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "description": {
      "type": "string"
    },
    "domain": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "rarity": {
      "type": "number"
    },
    "source": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "_id",
    "days",
    "description",
    "domain",
    "id",
    "location",
    "name",
    "rarity",
    "source"
  ],
  "type": "object",
  "additionalProperties": false
}

=== Sasikuttan2163/dvalin-data/data/IT/WeaponPrimaryMaterial/ChainsOfTheDandelionGladiator.json
{
	"_id": 114010,
	"id": "ChainsOfTheDandelionGladiator",
	"name": "Catene del Gladiatore dei denti di leone",
	"description": "Le catene che un tempo vincolavano la grande eroina Vennessa. In verità, a tutti i gladiatori erano messe delle catene a quel tempo, e Vennessa era solo una dei tanti.",
	"source": [
		"Creato"
	],
	"location": "Mondstadt",
	"rarity": 3,
	"craft": {
		"cost": 125,
		"items": [
			{
				"_id": 114009,
				"id": "FettersOfTheDandelionGladiator",
				"name": "Ferri del Gladiatore dei denti di leone",
				"amount": 3
			}
		]
	},
	"domain": "Giardino di Cecilie",
	"days": [
		"Mercoledì",
		"Sabato",
		"Domenica"
	]
}
